// PLANS
export const GET_PLANS = "GET_PLANS";
export const GET_PLAN = "GET_PLAN";
export const DELETE_PLAN = "DELETE_PLAN";
export const ADD_PLAN = "ADD_PLAN";
export const UPDATE_PLAN = "UPDATE_PLAN";

// COMPONENTS
export const GET_COMPONENTS = "GET_COMPONENTS";
export const GET_COMPONENT = "GET_COMPONENT";
export const DELETE_COMPONENT = "DELETE_COMPONENT";
export const ADD_COMPONENT = "ADD_COMPONENT";
export const UPDATE_COMPONENT = "UPDATE_COMPONENT";

// GROUPS
export const GET_GROUPS = "GET_GROUPS";
export const GET_GROUP = "GET_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const ADD_GROUP = "ADD_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";

// PARTICIPANTS
export const GET_PARTICIPANTS = "GET_PARTICIPANTS";
export const GET_PARTICIPANT = "GET_PARTICIPANT";
export const DELETE_PARTICIPANT = "DELETE_PARTICIPANT";
export const ADD_PARTICIPANT = "ADD_PARTICIPANT";
export const UPDATE_PARTICIPANT = "UPDATE_PARTICIPANT";

// RESPONSES
export const GET_RESPONSES = "GET_RESPONSES";
export const GET_RESPONSE = "GET_RESPONSE";
export const DELETE_RESPONSE = "DELETE_RESPONSE";
export const ADD_RESPONSE = "ADD_RESPONSE";
export const UPDATE_RESPONSE = "UPDATE_RESPONSE";
export const CLEAR_RESPONSES = "CLEAR_RESPONSES";

// RECORDINGS
export const GET_RECORDINGS = "GET_RECORDINGS";
export const GET_RECORDING = "GET_RECORDING";
export const DELETE_RECORDING = "DELETE_RECORDING";
export const ADD_RECORDING = "ADD_RECORDING";
export const UPDATE_RECORDING = "UPDATE_RECORDING";
export const CLEAR_RECORDINGS = "CLEAR_RECORDINGS";

// ALERTS
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

// AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

// LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

// Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

// REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"