// PLANS
export const GET_PLANS = "GET_PLANS";
export const GET_PLAN = "GET_PLAN";
export const DELETE_PLAN = "DELETE_PLAN";
export const ADD_PLAN = "ADD_PLAN";

// COMPONENTS
export const GET_COMPONENTS = "GET_COMPONENTS";
export const GET_COMPONENT = "GET_COMPONENT";
export const DELETE_COMPONENT = "DELETE_COMPONENT";
export const ADD_COMPONENT = "ADD_COMPONENT";

// PARTICIPANTS
export const GET_PARTICIPANTS = "GET_PARTICIPANTS";
export const GET_PARTICIPANT = "GET_PARTICIPANT";
export const DELETE_PARTICIPANT = "DELETE_PARTICIPANT";
export const ADD_PARTICIPANT = "ADD_PARTICIPANT";

// ALERTS
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

// AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

// LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

// Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

// REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"