// INTERVIEWS
export const GET_INTERVIEWS = "GET_INTERVIEWS";
export const DELETE_INTERVIEW = "DELETE_INTERVIEW";
export const ADD_INTERVIEW = "ADD_INTERVIEW";

// ALERTS
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

// AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

// LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

// Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

// REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"