# Generated by Django 2.2.6 on 2020-01-21 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0002_interview_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.Plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='interview',
            name='owner',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.Interview')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.Question')),
            ],
        ),
        migrations.CreateModel(
            name='InsightTagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insight_tag_types', to='interviews.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='InsightTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insight_tags', to='interviews.Response')),
                ('tag_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='interviews.InsightTagType')),
            ],
        ),
        migrations.CreateModel(
            name='DataTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_tags', to='interviews.Response')),
                ('tag_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='interviews.DataTagType')),
            ],
        ),
        migrations.CreateModel(
            name='BiasReflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_reflections', to='interviews.Interview')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_reflections', to='interviews.Question')),
            ],
        ),
        migrations.CreateModel(
            name='BiasDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_declarations', to='interviews.Interview')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_declarations', to='interviews.Question')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interviews.Plan'),
        ),
    ]
