# Generated by Django 2.2.6 on 2020-01-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20200121_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='interviews.Plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='biasdeclaration',
            name='question',
        ),
        migrations.RemoveField(
            model_name='biasreflection',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='biasdeclaration',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_declarations', to='interviews.Component'),
        ),
        migrations.AddField(
            model_name='biasreflection',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_reflections', to='interviews.Component'),
        ),
        migrations.AddField(
            model_name='response',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.Component'),
        ),
    ]
