# Generated by Django 2.2.6 on 2020-01-24 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0004_auto_20200124_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to=settings.AUTH_USER_MODEL),
        ),
    ]
