# Generated by Django 2.2.6 on 2020-01-24 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0005_component_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='interviews.Plan')),
            ],
        ),
        migrations.AlterField(
            model_name='biasdeclaration',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_declarations', to='interviews.Participant'),
        ),
        migrations.AlterField(
            model_name='biasreflection',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_reflections', to='interviews.Participant'),
        ),
        migrations.AlterField(
            model_name='response',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.Participant'),
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
