# Generated by Django 2.2.6 on 2020-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_auto_20200124_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
