# Generated by Django 2.2.6 on 2020-01-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_plan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
