# Generated by Django 2.2.6 on 2020-02-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_auto_20200203_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='interviews.Plan'),
        ),
    ]
