# Generated by Django 2.2.6 on 2020-02-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_component_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
