# Generated by Django 2.2.6 on 2020-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0013_auto_20200204_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biasdeclaration',
            old_name='interview',
            new_name='participant',
        ),
        migrations.RenameField(
            model_name='biasreflection',
            old_name='interview',
            new_name='participant',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='interview',
            new_name='participant',
        ),
        migrations.RemoveField(
            model_name='biasdeclaration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='biasreflection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='response',
            name='name',
        ),
        migrations.AddField(
            model_name='biasdeclaration',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='biasreflection',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
