# Generated by Django 2.2.6 on 2020-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0015_auto_20200206_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
