# Generated by Django 2.2.6 on 2020-02-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0016_participant_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='permitRecording',
            field=models.BooleanField(default=True),
        ),
    ]
