# Generated by Django 2.2.6 on 2020-02-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0018_auto_20200216_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='length',
            field=models.IntegerField(default=-1),
        ),
    ]
