# Generated by Django 2.2.6 on 2020-02-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0020_auto_20200216_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='automaticRecording',
            field=models.BooleanField(default=False),
        ),
    ]
