# Generated by Django 2.2.6 on 2020-02-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0021_plan_automaticrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
    ]
