# Generated by Django 2.2.6 on 2020-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0023_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
