# Generated by Django 2.2.6 on 2020-02-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0025_auto_20200221_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='interviews.Participant'),
        ),
    ]
