# Generated by Django 2.2.6 on 2020-02-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0027_response_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='link_note',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
