# Generated by Django 2.2.6 on 2020-02-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0028_response_link_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='text',
        ),
    ]
