# Generated by Django 2.2.6 on 2020-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0030_plan_biasreflection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasdeclaration',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='biasreflection',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
