# Generated by Django 2.2.6 on 2020-02-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0031_auto_20200224_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasreflection',
            name='confirmed_expectations',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
