# Generated by Django 2.2.6 on 2020-03-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0033_auto_20200306_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coding',
            name='name',
        ),
    ]
